# Generated by Django 4.2.11 on 2024-03-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_privatetasks_privatetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatetask',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
