# Generated by Django 4.2.11 on 2024-04-02 19:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoprojects', '0005_projecttask_delete_privatetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('color', models.CharField(choices=[('white', 'White'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red')], max_length=16)),
                ('date', models.DateField(default=datetime.date.today)),
                ('hour', models.TimeField(default=datetime.time(23, 59))),
                ('done', models.BooleanField(default=False)),
                ('notification', models.CharField(choices=[('kicked', 'Kick'), ('invited', 'Invite'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoprojects.project')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
